name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: kekw
      run: php -v
    - name: kekw1
      run: ls
    - name: smotrim secretic
      run: echo ${{ secrets.PROD_IP }} > test.log | cat test.log
    - name: where i am
      run: cd .. | ls
    - name: whoami
      run: whoami
    - name: ssh-smotrim
      run: eval `ssh-agent`
